### ISSUE TITLE
Look into fixing on RHEL: ModuleNotFoundError: No module named 'myst_parser'

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#492] opened 2024-05-17 08:20 UTC
On RHEL we see [this error](https://github.com/fedora-llvm-team/llvm-snapshots/issues/491#issuecomment-2116518620) and I believe there used to be a fix for this.

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/config.py", line 326, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/builddir/build/BUILD/llvm-project-ec36145f58d2cf93d86bc4e3be617ad7d7d8ace7/llvm/redhat-linux-build/tools/clang/docs/conf.py", line 42, in <module>
    import myst_parser
ModuleNotFoundError: No module named 'myst_parser'
```

**Comment by nikic** [comment] 2024-05-22 07:20
There used to be RHEL-specific patches for this. Tom dropped them in https://src.fedoraproject.org/rpms/llvm/c/3b035c500e3e5d09485efef1b8bc8aae2967edbe?branch=big-merge. The referenced commit is https://github.com/llvm/llvm-project/commit/7d55a3ba92368be55b392c20d623fde6ac82d86d.

I think the problem is that this only allows myst_parser to be absent when building man pages, but we also build non-manpage docs.

**Comment by nikic** [comment] 2024-05-23 05:27
Fixed by https://src.fedoraproject.org/rpms/llvm/pull-request/210.

**Closed by nikic** 2024-05-23 05:27 UTC
Labels: python, os/rhel-9
